# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.
CHIAPIKEY ="XTzcaicIeaM3s1GDqbUAaUVS5"

development:
  secret_key_base: 55b8c21f1c114ce4d2ddf88c7624aa2ebce4b095e86ba84675888df201a88a72c7dc29335445f4371c6c876334850580a032246467b4902d3b4247f50059282a

test:
  secret_key_base: e8683a049b39bc5013c6ac2b4739799185bccfce54fcf5f1a2330b23a1b150e95c075053b8052c5f45f6cf2b1af8fa137d22c45a7f56ff74cfe06461b76bda35

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
